#App
appTitle=ETM
appDescription=Equipment and Tools Management

#Languages
english=English
german=German
romanian=Romanian
portuguese=Portuguese
portugueseBrazil=Portuguese (Brazil)
portuguesePortugal=Portuguese (Portugal)
french=French
czech=Czech